"""added gender table and relationships

Revision ID: 0b0146b23035
Revises: 1baf215d1b24
Create Date: 2022-05-02 12:44:15.320532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0146b23035'
down_revision = '1baf215d1b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_user_gender", 'gender', ['gender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_gender", type_='foreignkey')
        batch_op.drop_column('gender_id')

    # ### end Alembic commands ###
